server:
  port: 8123

spring:
  application:
    name: gateway  
  cloud:
    gateway:
      routes:
      - id: book-svc
        uri: lb://book-service
        predicates:
        - Path=/booksvc/**
        filters:
        - StripPrefix=1
#      - id: rating-svc
#        uri: lb://rating-service
#        predicates:
#        - Path=/ratingsvc/**
#        filters:
#        - StripPrefix=1
    # config:
    #   import-check:
    #     enabled: false

eureka:
  client:
    registerWithEureka: true
    # serviceUrl: 
    #   defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    healthcheck:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include:
          - mappings
          - env
          - health
          - info
          - refresh
  info:
    env:
      enabled: true

info:
  app:
    name: ${spring.application.name}
